---
- name: daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: set directory permissions
  ansible.builtin.file:
    path: "{{ uptime_kuma_installation_directory }}"
    state: directory
    recurse: true
    owner: "{{ uptime_kuma_user }}"
    group: "{{ uptime_kuma_user }}"
  notify: restart uptime-kuma

- name: restart uptime-kuma
  ansible.builtin.service:
    name: uptime-kuma.service
    state: restarted
