---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: python:3-bullseye
    pre_build_image: true
    published_ports:
      - 80:80
      - 443:443
      - 8080:8080
provisioner:
  name: ansible
verifier:
  name: ansible
